/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as ThankYouRouteImport } from "./routes/thank-you"
import { Route as TermsRouteImport } from "./routes/terms"
import { Route as SitemapDotxmlRouteImport } from "./routes/sitemap[.]xml"
import { Route as ShopRouteImport } from "./routes/shop"
import { Route as RefundRouteImport } from "./routes/refund"
import { Route as PrivacyRouteImport } from "./routes/privacy"
import { Route as OfferRouteImport } from "./routes/offer"
import { Route as LoginRouteImport } from "./routes/login"
import { Route as ContactRouteImport } from "./routes/contact"
import { Route as CheckoutRouteImport } from "./routes/checkout"
import { Route as AboutRouteImport } from "./routes/about"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as AdminIndexRouteImport } from "./routes/admin.index"
import { Route as OfferSlugRouteImport } from "./routes/offer.$slug"
import { Route as AdminSettingsRouteImport } from "./routes/admin.settings"
import { Route as AdminProductsRouteImport } from "./routes/admin.products"
import { Route as AdminOrdersRouteImport } from "./routes/admin.orders"
import { Route as AdminLeadsRouteImport } from "./routes/admin.leads"
import { Route as ApiPublicStripeWebhookRouteImport } from "./routes/api/public/stripe-webhook"

const ThankYouRoute = ThankYouRouteImport.update({
  id: "/thank-you",
  path: "/thank-you",
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: "/terms",
  path: "/terms",
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: "/sitemap.xml",
  path: "/sitemap.xml",
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: "/shop",
  path: "/shop",
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: "/refund",
  path: "/refund",
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: "/privacy",
  path: "/privacy",
  getParentRoute: () => rootRouteImport,
} as any)
const OfferRoute = OfferRouteImport.update({
  id: "/offer",
  path: "/offer",
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: "/contact",
  path: "/contact",
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: "/checkout",
  path: "/checkout",
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: "/about",
  path: "/about",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: "/admin/",
  path: "/admin/",
  getParentRoute: () => rootRouteImport,
} as any)
const OfferSlugRoute = OfferSlugRouteImport.update({
  id: "/$slug",
  path: "/$slug",
  getParentRoute: () => OfferRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: "/admin/settings",
  path: "/admin/settings",
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: "/admin/products",
  path: "/admin/products",
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: "/admin/orders",
  path: "/admin/orders",
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: "/admin/leads",
  path: "/admin/leads",
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: "/api/public/stripe-webhook",
  path: "/api/public/stripe-webhook",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/about": typeof AboutRoute
  "/checkout": typeof CheckoutRoute
  "/contact": typeof ContactRoute
  "/login": typeof LoginRoute
  "/offer": typeof OfferRouteWithChildren
  "/privacy": typeof PrivacyRoute
  "/refund": typeof RefundRoute
  "/shop": typeof ShopRoute
  "/sitemap.xml": typeof SitemapDotxmlRoute
  "/terms": typeof TermsRoute
  "/thank-you": typeof ThankYouRoute
  "/admin/leads": typeof AdminLeadsRoute
  "/admin/orders": typeof AdminOrdersRoute
  "/admin/products": typeof AdminProductsRoute
  "/admin/settings": typeof AdminSettingsRoute
  "/offer/$slug": typeof OfferSlugRoute
  "/admin/": typeof AdminIndexRoute
  "/api/public/stripe-webhook": typeof ApiPublicStripeWebhookRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/about": typeof AboutRoute
  "/checkout": typeof CheckoutRoute
  "/contact": typeof ContactRoute
  "/login": typeof LoginRoute
  "/offer": typeof OfferRouteWithChildren
  "/privacy": typeof PrivacyRoute
  "/refund": typeof RefundRoute
  "/shop": typeof ShopRoute
  "/sitemap.xml": typeof SitemapDotxmlRoute
  "/terms": typeof TermsRoute
  "/thank-you": typeof ThankYouRoute
  "/admin/leads": typeof AdminLeadsRoute
  "/admin/orders": typeof AdminOrdersRoute
  "/admin/products": typeof AdminProductsRoute
  "/admin/settings": typeof AdminSettingsRoute
  "/offer/$slug": typeof OfferSlugRoute
  "/admin": typeof AdminIndexRoute
  "/api/public/stripe-webhook": typeof ApiPublicStripeWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/about": typeof AboutRoute
  "/checkout": typeof CheckoutRoute
  "/contact": typeof ContactRoute
  "/login": typeof LoginRoute
  "/offer": typeof OfferRouteWithChildren
  "/privacy": typeof PrivacyRoute
  "/refund": typeof RefundRoute
  "/shop": typeof ShopRoute
  "/sitemap.xml": typeof SitemapDotxmlRoute
  "/terms": typeof TermsRoute
  "/thank-you": typeof ThankYouRoute
  "/admin/leads": typeof AdminLeadsRoute
  "/admin/orders": typeof AdminOrdersRoute
  "/admin/products": typeof AdminProductsRoute
  "/admin/settings": typeof AdminSettingsRoute
  "/offer/$slug": typeof OfferSlugRoute
  "/admin/": typeof AdminIndexRoute
  "/api/public/stripe-webhook": typeof ApiPublicStripeWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/about"
    | "/checkout"
    | "/contact"
    | "/login"
    | "/offer"
    | "/privacy"
    | "/refund"
    | "/shop"
    | "/sitemap.xml"
    | "/terms"
    | "/thank-you"
    | "/admin/leads"
    | "/admin/orders"
    | "/admin/products"
    | "/admin/settings"
    | "/offer/$slug"
    | "/admin/"
    | "/api/public/stripe-webhook"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/about"
    | "/checkout"
    | "/contact"
    | "/login"
    | "/offer"
    | "/privacy"
    | "/refund"
    | "/shop"
    | "/sitemap.xml"
    | "/terms"
    | "/thank-you"
    | "/admin/leads"
    | "/admin/orders"
    | "/admin/products"
    | "/admin/settings"
    | "/offer/$slug"
    | "/admin"
    | "/api/public/stripe-webhook"
  id:
    | "__root__"
    | "/"
    | "/about"
    | "/checkout"
    | "/contact"
    | "/login"
    | "/offer"
    | "/privacy"
    | "/refund"
    | "/shop"
    | "/sitemap.xml"
    | "/terms"
    | "/thank-you"
    | "/admin/leads"
    | "/admin/orders"
    | "/admin/products"
    | "/admin/settings"
    | "/offer/$slug"
    | "/admin/"
    | "/api/public/stripe-webhook"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  OfferRoute: typeof OfferRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  RefundRoute: typeof RefundRoute
  ShopRoute: typeof ShopRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  ThankYouRoute: typeof ThankYouRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/thank-you": {
      id: "/thank-you"
      path: "/thank-you"
      fullPath: "/thank-you"
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/terms": {
      id: "/terms"
      path: "/terms"
      fullPath: "/terms"
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/sitemap.xml": {
      id: "/sitemap.xml"
      path: "/sitemap.xml"
      fullPath: "/sitemap.xml"
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/shop": {
      id: "/shop"
      path: "/shop"
      fullPath: "/shop"
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/refund": {
      id: "/refund"
      path: "/refund"
      fullPath: "/refund"
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/privacy": {
      id: "/privacy"
      path: "/privacy"
      fullPath: "/privacy"
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/offer": {
      id: "/offer"
      path: "/offer"
      fullPath: "/offer"
      preLoaderRoute: typeof OfferRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/login": {
      id: "/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/contact": {
      id: "/contact"
      path: "/contact"
      fullPath: "/contact"
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/checkout": {
      id: "/checkout"
      path: "/checkout"
      fullPath: "/checkout"
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/about": {
      id: "/about"
      path: "/about"
      fullPath: "/about"
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/admin/": {
      id: "/admin/"
      path: "/admin"
      fullPath: "/admin/"
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/offer/$slug": {
      id: "/offer/$slug"
      path: "/$slug"
      fullPath: "/offer/$slug"
      preLoaderRoute: typeof OfferSlugRouteImport
      parentRoute: typeof OfferRoute
    }
    "/admin/settings": {
      id: "/admin/settings"
      path: "/admin/settings"
      fullPath: "/admin/settings"
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/admin/products": {
      id: "/admin/products"
      path: "/admin/products"
      fullPath: "/admin/products"
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/admin/orders": {
      id: "/admin/orders"
      path: "/admin/orders"
      fullPath: "/admin/orders"
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/admin/leads": {
      id: "/admin/leads"
      path: "/admin/leads"
      fullPath: "/admin/leads"
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/api/public/stripe-webhook": {
      id: "/api/public/stripe-webhook"
      path: "/api/public/stripe-webhook"
      fullPath: "/api/public/stripe-webhook"
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface OfferRouteChildren {
  OfferSlugRoute: typeof OfferSlugRoute
}

const OfferRouteChildren: OfferRouteChildren = {
  OfferSlugRoute: OfferSlugRoute,
}

const OfferRouteWithChildren = OfferRoute._addFileChildren(OfferRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  OfferRoute: OfferRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  RefundRoute: RefundRoute,
  ShopRoute: ShopRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  ThankYouRoute: ThankYouRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from "./router.tsx"
import type { startInstance } from "./start.ts"
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
