-- ─────────────────────────────────────────────────────────────
--  Luveni GM — product-media storage bucket
--
--  Public bucket that holds background-removed transparent product PNGs
--  generated by the admin "Make Transparent" tool (CjTransparencyPanel).
--  Reads are public (the storefront <img> loads them); writes/updates are
--  restricted to admins so the browser tool can upload straight from the
--  admin's authenticated session without a service-role round-trip.
--
--  Additive + idempotent.
-- ─────────────────────────────────────────────────────────────

insert into storage.buckets (id, name, public)
values ('product-media', 'product-media', true)
on conflict (id) do update set public = true;

-- Public read (anyone can view a product image).
do $$ begin
  create policy "product-media public read"
    on storage.objects for select
    using (bucket_id = 'product-media');
exception when duplicate_object then null; end $$;

-- Admin write/update/delete (the browser tool uploads as the admin user).
do $$ begin
  create policy "product-media admin insert"
    on storage.objects for insert to authenticated
    with check (bucket_id = 'product-media' and public.has_role(auth.uid(), 'admin'));
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "product-media admin update"
    on storage.objects for update to authenticated
    using (bucket_id = 'product-media' and public.has_role(auth.uid(), 'admin'))
    with check (bucket_id = 'product-media' and public.has_role(auth.uid(), 'admin'));
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "product-media admin delete"
    on storage.objects for delete to authenticated
    using (bucket_id = 'product-media' and public.has_role(auth.uid(), 'admin'));
exception when duplicate_object then null; end $$;
